services:

 db:
   container_name: db
   image: mysql:latest
   security_opt:
     - no-new-privileges:true
   restart: always
   volumes:
     - db_data:/var/lib/mysql
   expose:
     - "3306"
   ports:
     - 3306:3306
   environment:
    MYSQL_DATABASE: 'apidb'
    # So you don't have to use root, but you can if you like
    MYSQL_USER: 'ferhat'
    # You can use whatever password you like
    MYSQL_PASSWORD: '4mvdfgdfgAvkdfgzzsOMG5fh'
    # Password for root access
    MYSQL_ROOT_PASSWORD: 4mvstWAvkShcgsOMG5fh


volumes:
  db_data: